/*********************************************************************
* Software License Agreement (BSD License)
* 
*  Copyright (c) 2018, The MITRE Corporation.
*  All rights reserved.
* 
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
* 
*   * Redistributions of source code must retain the above copyright
*     notice, this list of conditions and the following disclaimer.
*   * Redistributions in binary form must reproduce the above
*     copyright notice, this list of conditions and the following
*     disclaimer in the documentation and/or other materials provided
*     with the distribution.
*   * Neither the name of The MITRE Corporation nor the names of its
*     contributors may be used to endorse or promote products derived
*     from this software without specific prior written permission.
* 
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
*  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
*  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
*  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
*  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
*  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
*  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
*  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
*  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
*  POSSIBILITY OF SUCH DAMAGE.
*********************************************************************/

#pragma once
/**
 * @file masking_node.h
 * @brief The OpenVX custom image masking kernel
 * @author Zach LaCelle (zlacelle@mitre.org)
 */

/**
 * @brief The OpenVX Masking node constructor.
 * @param [in] _graph The OpenVX graph which will contain this node.
 * @param [in] _input The OpenVX image on which we're generating a mask
 * @param [in] _startX The starting X index in the image, in pixels
 * @param [in] _startY The starting Y index in the image, in pixels
 * @param [in] _width The width of the mask, in pixels
 * @param [in] _height The height of the mask, in pixels
 * @param [in] _maskingValue The value to apply to pixels which lie inside of the masked area
 * @return The OpenVX node which was generated by this call
 */
vx_node ImageMaskingNode( vx_graph _graph,
                          vx_image _input,
                          vx_uint32 _startX,
                          vx_uint32 _startY,
                          vx_uint32 _width,
                          vx_uint32 _height,
                          vx_uint8 _maskingValue);

/**
 * @brief Register the Masking kernel with the provided OpenVX context
 * @param _context The OpenVX context within which we'll register the kernel
 * @return The status of the kernel registration attempt
 */
vx_status RegisterImageMaskingKernel( vx_context _context );
