/*********************************************************************
* Software License Agreement (BSD License)
* 
*  Copyright (c) 2018, The MITRE Corporation.
*  All rights reserved.
* 
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
* 
*   * Redistributions of source code must retain the above copyright
*     notice, this list of conditions and the following disclaimer.
*   * Redistributions in binary form must reproduce the above
*     copyright notice, this list of conditions and the following
*     disclaimer in the documentation and/or other materials provided
*     with the distribution.
*   * Neither the name of The MITRE Corporation nor the names of its
*     contributors may be used to endorse or promote products derived
*     from this software without specific prior written permission.
* 
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
*  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
*  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
*  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
*  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
*  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
*  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
*  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
*  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
*  POSSIBILITY OF SUCH DAMAGE.
*********************************************************************/

#pragma once
/**
 * @file sobel_filter_node.h
 * @brief The OpenVX custom sobel filter kernel
 * @author Zach LaCelle (zlacelle@mitre.org)
 */

/**
 * @brief The OpenVX Sobel Filter node constructor
 * @param [in] _graph The OpenVX graph which will contain this node
 * @param [in] _leftIn The OpenVX image, left camera
 * @param [in] _rightIn The OpenVX image, right camera
 * @param [out] _leftOut The OpenVX output image, left camera
 * @param [out] _rightOut The OpenVX output image, right camera
 * @param [in] _prefilterCap The prefilter cap (?)
 * @return The OpenVX node which was generated by this call
 */
vx_node SobelFilterNode( vx_graph _graph,
                         vx_image _leftIn,
                         vx_image _rightIn,
                         vx_image _leftOut,
                         vx_image _rightOut,
                         vx_uint32 _prefilterCap);

/**
 * @brief Register the Sobel Filter kernel with the provided OpenVX context
 * @param _context The OpenVX context within which we'll register the kernel
 * @return The status of the kernel registration attempt
 */
vx_status RegisterSobelFilterKernel( vx_context _context );

/**
 * @brief Helper function, copied from OpenCV stereobm.cpp, which performs
 * the filtering.
 *
 * Custom license, see comments in cpp file.
 *
 * @param [in] _src The image source mat
 * @param [out] _dst The image destination mat
 * @param [in] _ftzero The prefilter cap parameter
 */
void OpenCVPrefilterXSobel(cv::Mat _src, cv::Mat _dst, int _ftzero);
